######################################################################################################################################################
# $$$$$$$\                                    $$\           $$$$$$$\  $$\                     $$\       $$\                                          #
# $$  __$$\                                   \__|          $$  __$$\ \__|                    \__|      $$ |                                         #
# $$ |  $$ | $$$$$$\  $$$$$$\$$$$\   $$$$$$\  $$\ $$$$$$$\  $$ |  $$ |$$\  $$$$$$$\  $$$$$$$\ $$\  $$$$$$$ | $$$$$$\  $$$$$$$\   $$$$$$$\  $$$$$$\   #
# $$ |  $$ |$$  __$$\ $$  _$$  _$$\  \____$$\ $$ |$$  __$$\ $$ |  $$ |$$ |$$  _____|$$  _____|$$ |$$  __$$ |$$  __$$\ $$  __$$\ $$  _____|$$  __$$\  #
# $$ |  $$ |$$ /  $$ |$$ / $$ / $$ | $$$$$$$ |$$ |$$ |  $$ |$$ |  $$ |$$ |\$$$$$$\  \$$$$$$\  $$ |$$ /  $$ |$$$$$$$$ |$$ |  $$ |$$ /      $$$$$$$$ | #
# $$ |  $$ |$$ |  $$ |$$ | $$ | $$ |$$  __$$ |$$ |$$ |  $$ |$$ |  $$ |$$ | \____$$\  \____$$\ $$ |$$ |  $$ |$$   ____|$$ |  $$ |$$ |      $$   ____| #
# $$$$$$$  |\$$$$$$  |$$ | $$ | $$ |\$$$$$$$ |$$ |$$ |  $$ |$$$$$$$  |$$ |$$$$$$$  |$$$$$$$  |$$ |\$$$$$$$ |\$$$$$$$\ $$ |  $$ |\$$$$$$$\ \$$$$$$$\  #
# \_______/  \______/ \__| \__| \__| \_______|\__|\__|  \__|\_______/ \__|\_______/ \_______/ \__| \_______| \_______|\__|  \__| \_______| \_______| #
######################################################################################################################################################

# BRANDING
[branding]
title="FakeName"
description="Find the best deals around!"

# COLORS
[colors]
primary="#FF6060"
secondary="#F0F0F0"

# COMPANY BOYCOTT LIST
[[company]]
name="CompanyName1"
logoURL="https://exampleimages.com/companyname1logo.png"

